#!/bin/bash

# Check if uv is installed
if ! command -v uv &> /dev/null; then
    echo "uv could not be found. Please install uv before running this script."
    exit 1
fi

# Prompt for project name if not provided as an argument
if [ -z "$1" ]; then
  read -p "Enter the project name: " PROJECT_NAME
else
  PROJECT_NAME=$1
fi

SETTINGS_FILE="$PROJECT_NAME/settings.py"
URLS_FILE="$PROJECT_NAME/urls.py"

mkdir -p "$PROJECT_NAME"
cd "$PROJECT_NAME"

uv init .

rm -rf main.py

uv add django django-environ django-tailwind-cli whitenoise django-browser-reload django-debug-toolbar

uv run django-admin startproject "$PROJECT_NAME" .

# --- Environment configuration with django-environ ---

# Capture the secret key generated by startproject before replacing it in settings
SECRET_KEY_VALUE=$(grep '^SECRET_KEY = ' "$SETTINGS_FILE" | sed -E 's/^SECRET_KEY = //; s/^["'\'']//; s/["'\'']$//')

# Import environ right after the pathlib import
sed -i '' "/^from pathlib import Path/a\\
import environ
" "$SETTINGS_FILE"

# Initialize the Env object and read the .env file right after BASE_DIR is defined
sed -i '' "/^BASE_DIR = Path(__file__).resolve().parent.parent/a\\
\\
env = environ.Env(\\
    DEBUG=(bool, False),\\
    ALLOWED_HOSTS=(list, ['127.0.0.1', 'localhost']),\\
)\\
environ.Env.read_env(BASE_DIR / '.env')
" "$SETTINGS_FILE"

# Read SECRET_KEY, DEBUG and ALLOWED_HOSTS from the environment
sed -i '' 's|^SECRET_KEY = .*|SECRET_KEY = env("SECRET_KEY")|' "$SETTINGS_FILE"
sed -i '' 's|^DEBUG = .*|DEBUG = env("DEBUG")|' "$SETTINGS_FILE"
sed -i '' 's|^ALLOWED_HOSTS = .*|ALLOWED_HOSTS = env("ALLOWED_HOSTS")|' "$SETTINGS_FILE"

# Configure the database from DATABASE_URL (defaults to local sqlite)
perl -0pi -e 's/DATABASES = \{.*?\n\}\n/DATABASES = {\n    "default": env.db(default=f"sqlite:\/\/\/{BASE_DIR \/ '"'"'db.sqlite3'"'"'}"),\n}\n/s' "$SETTINGS_FILE"

# Add apps to INSTALLED_APPS around 'django.contrib.staticfiles'
sed -i '' "/'django.contrib.staticfiles',/i\\
    'whitenoise.runserver_nostatic',
" "$SETTINGS_FILE"

sed -i '' "/'django.contrib.staticfiles',/a\\
    'django_tailwind_cli',\\
    'django_browser_reload',\\
    'debug_toolbar',
" "$SETTINGS_FILE"

# Add WhiteNoise middleware after SecurityMiddleware
sed -i '' "/'django.middleware.security.SecurityMiddleware',/a\\
    'whitenoise.middleware.WhiteNoiseMiddleware',
" "$SETTINGS_FILE"

# Add BrowserReload middleware after XFrameOptionsMiddleware
sed -i '' "/'django.middleware.clickjacking.XFrameOptionsMiddleware',/a\\
    'django_browser_reload.middleware.BrowserReloadMiddleware',\\
    'debug_toolbar.middleware.DebugToolbarMiddleware',
" "$SETTINGS_FILE"

# Add templates dir to TEMPLATES DIRS
sed -i '' "s|'DIRS': \[\]|'DIRS': [BASE_DIR / 'templates']|" "$SETTINGS_FILE"

# Add static and tailwind settings after STATIC_URL
sed -i '' "/^STATIC_URL = /a\\
STATIC_ROOT = BASE_DIR / 'static'\\
STATICFILES_DIRS = [BASE_DIR / 'assets']\\
TAILWIND_CLI_SRC_CSS = BASE_DIR / 'src' / 'styles' / 'main.css'\\
# TAILWIND_CLI_USE_DAISY_UI = True
" "$SETTINGS_FILE"

# Add STORAGES setting at the end of the file
cat <<EOL >> "$SETTINGS_FILE"

STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

if DEBUG:
    INTERNAL_IPS = [
        "127.0.0.1",
    ]

EOL

# Add "include" to the import
sed -i '' 's|from django.urls import path|from django.urls import path, include|' "$URLS_FILE"

# Import settings
sed -i '' "/^from django.urls import path, include/a\\
from django.conf import settings
" "$URLS_FILE"

# Add django_browser_reload to urlpatterns
sed -i '' "/^urlpatterns = \[/a\\
    path('__reload__/', include('django_browser_reload.urls')),
" "$URLS_FILE"

# Add debug_toolbar_urls to urlpatterns
cat <<EOL >> "$URLS_FILE"

if settings.DEBUG:
    from debug_toolbar.toolbar import debug_toolbar_urls
    urlpatterns = urlpatterns + debug_toolbar_urls()
EOL

# Create necessary directories for assets, templates, static files, and styles
mkdir -p assets
mkdir -p templates
mkdir -p static
mkdir -p src/styles

# Create base.html
cat <<EOL > templates/base.html
{% load tailwind_cli %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Django App</title>
    {% tailwind_css %}
</head>
<body>
    {% block main_content %}{% endblock %}
</body>
</html>
EOL

cat <<EOL > src/styles/main.css
@import "tailwindcss";

/*@plugin "daisyui" {
  themes: light --default, dark --prefersdark;
}*/
EOL

# Create the local .env file (ignored by git) with the generated secret key
cat <<EOL > .env
DEBUG=True
SECRET_KEY=$SECRET_KEY_VALUE
ALLOWED_HOSTS=127.0.0.1,localhost
DATABASE_URL=sqlite:///db.sqlite3
EOL

# Create a committed template describing the required environment variables
cat <<EOL > .env.example
DEBUG=False
SECRET_KEY=
ALLOWED_HOSTS=example.com,www.example.com
DATABASE_URL=postgres://user:password@host:5432/dbname
EOL

# Make sure the local .env is never committed
if [ -f .gitignore ]; then
  grep -qxF '.env' .gitignore || echo '.env' >> .gitignore
else
  echo '.env' > .gitignore
fi

